sudo: required
services:
  - docker

before_install:
  - docker build -t rajeshgoyalg/react-in-container -f Dockerfile.dev .

script:
  - docker run -e CI=true rajeshgoyalg/react-in-container npm run test